apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nostr-rs-relay.fullname" . }}
  labels:
    {{- include "nostr-rs-relay.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nostr-rs-relay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nostr-rs-relay.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nostr-rs-relay.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: "/usr/src/app/db"
            name: nostr-data
            readOnly: false
          - mountPath: "/usr/src/app/config.toml"
            subPath: "config.toml"
            name: nostr-config
          # command: ["./"]
          # args: ["--config", "/usr/src/app/config.toml"]
      volumes:
        - name: nostr-data
          # emptyDir:
          #   sizeLimit: 10Gi
          persistentVolumeClaim:
            claimName: {{ include "nostr-rs-relay.fullname" . }}
        - name: nostr-config
          configMap:
            name: {{ include "nostr-rs-relay.fullname" . }}
      securityContext:
        runAsUser: 100
        runAsGroup: 100
        fsGroup: 100
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
