{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lnbits.fullname" . }}-config
  namespace: default
data:
  .env: |
    {{ .Values.config.data | nindent 4 }}
{{- end }}