# Kubernetes Persistent Volume Claim
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "lnbits.fullname" . }}-data
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.persistence.size }}
{{- end }}